### PR TITLE
Add nix to manage required tools for build

### PR DESCRIPTION
**Pull request by dasormeter**
- Add nix to manage required tools for build
  - jq
  - make
  - node
  - npm
  - pip3
  - pipenv
  - python
  - python3
  - yarn
  - yq

- Correct yq syntax for v4

### CODE REVIEW

**Review by alexmatson-da — APPROVED** [review]
lgtm overall, but it could perhaps use some notes in the README on how to build the app with this

**Comment by dasormeter** [comment]
> lgtm overall, but it could perhaps use some notes in the README on how to build the app with this

Shouldn't be anything special required beyond what is in the README for the building as all the tools needs get loaded / build dynamically.

But good point that we do need to say install nix before running for the first time

**Review by alexgraham-da — APPROVED** [review]
lgtm as well, agreed on adding to the `README`

**Comment by dasormeter** [comment]
> lgtm as well, agreed on adding to the `README`

@alexgraham-da / @alexmatson-da readme updates are here https://github.com/digital-asset/da-marketplace/pull/463/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 -- can one of you try these instructions if you don't already have nix installed and see if they work?

**Comment by dasormeter** [comment]
don't think we want to go all the way with nix here

**Pull request closed without merging**
