### PR TITLE
run tests in CircleCI job

### PR DESCRIPTION
**Pull request by richardkapolnai-da**

### CODE REVIEW

**Comment by richardkapolnai-da** [comment]
Need to wait until dependencies are open sourced...

**Comment by lucianojoublanc-da** [comment]
Once #306 is in, you can try re-running the CI, and I think it should work.

**Comment by lucianojoublanc-da** [comment]
I just tried re-running it, but it's still pointing at the old repo. You'll need to rebase to sales-eng HEAD first I think.

**Review by alexmatson-da — APPROVED** [review]
This looks good to me, I can merge after the tests pass

**Pull request merged**
